version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: invest_news_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: news_aggregator
    ports:
      - "5432:5432" # Открываем порт, чтобы Go мог подключиться
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: